<div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 p-5 bg-light">
        <h1 class="display-3">Анализатор страниц</h1>
        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        <form action="/urls" method="post" class="row">
            <div class="col-8">
                <input type="text" name="url" value="" class="form-control form-control-lg" placeholder="https://www.example.com">
            </div>
            <div class="col-4">
                <button type="submit" class="btn btn-primary btn-lg px-5 text-uppercase">Проверить</button>
            </div>
        </form>
    </div>
</div>
