<div class="row">
    <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 p-5 bg-light">
        <h1 class="display-3">Анализатор страниц</h1>
        <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
        <form action="<?= $router->urlFor('url_store') ?>" method="post" class="row">
            <div class="col-8">
                <input type="text" name="url" value="<?= htmlspecialchars($url) ?>" class="form-control form-control-lg <?= isset($errors['url']) ? 'is-invalid' : '' ?>" placeholder="https://www.example.com">
                 <?php if (isset($errors['url'])): ?>
                    <div class="invalid-feedback">
                        <?= implode(', ', $errors['url']) ?>
                     </div>
<?php endif; ?>
            </div>
            <div class="col-4">
                <input type="submit" class="btn btn-primary btn-lg px-5 text-uppercase" value="Проверить">
            </div>
        </form>
    </div>
</div>
